[build]
  command = "yarn deploy"
  publish = "out"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/issues"
  to = "https://github.com/wilrnh/emergencywalletcards.com/issues"